spring:
  config:
    activate:
      on-profile: default
  application:
    name: cm-pot-svc
  main:
    allow-bean-definition-overriding: true
  jta:
    transaction-manager-id: transactionManager
  transaction:
    default-timeout: 30s
  datasource:
    # hikari:
    #   driver-class-name: oracle.jdbc.driver.OracleDriver
    #   username: APP_CM
    #   password: app_cm12!
    # url: jdbc:oracle:thin:@10.90.151.73:1521/QZEN
    # initialization-mode: never
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost:8082/test
    username: sa
    password:
    schema: classpath*:h2/schema.sql
    initialization-mode: always